build:
  environment:
    php:
      version: 5.4 # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=clover.xml tests'
        coverage:
          file: 'clover.xml'
          format: 'php-clover'
checks:
  php:
    custom_coding_standard:
      ruleset_path: 'ruleset.xml'
