language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

install:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpcs --standard=PSR2 src
